<?php 

/**
  * @file
  * Build page and form "contacts".
  */


/**
 * Implements hook_menu()
 */
function my_forms_menu() {
  $items = array();
  $items['contacts'] = array(
    'title' => t('module with form'),
    'description' => 'A form to mess around with.',
    'page callback' => 'my_forms_callback',
    'access callback' => TRUE,
    'menu_name' => 'menu-done',  // provides munu item.
  );
  $items['custom-form'] = array(
    'title' => t('Try form from "examples"'),
    'description' => 'A form to mess around with.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('my_form_from_example_states_form'),
    'access callback' => TRUE,
    'file' => 'my_form_from_example_states.inc',
  );
  return $items;
}

/*-----------------------------------------------------------------------*/

/**
 * Implements hook_form_alter()
 */
function my_forms_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'my_forms_form') {
    $form['message']['#rows'] = 3;
    //dsm($form_id); // показывает ID формы
    //dsm($form); 
  }

  if ($form_id == 'webform_client_form_21') {
    //$form['#submit'][] = 'webform_client_form_21_extra_submit';
    $form['actions']['submit']['#submit'][] = 'webform_client_form_21_extra_submit';
    $form['actions']['submit']['#validate'][] = 'webform_client_form_21_extra_validate';
  }
}

function webform_client_form_21_extra_validate($form, &$form_state) {
  $phone_number = $form_state['values']['submitted']['phone_number'];
  if (!($phone_number > 0) || strlen((string) $phone_number) < 12) {
    if (!empty($form_state['values']['submitted']['phone_number'])) {
      form_set_error('phone_number', t('check your phone number'));
    }   
  }
}

function webform_client_form_21_extra_submit($form, &$form_state) { 
  //dsm($form_state['values']['submitted']);
  drupal_set_message(t('The form has been submitted.<br>'
    . $form_state['values']['submitted']['firstname'] . '<br>'
    . $form_state['values']['submitted']['secondname'] . '<br>'
    . $form_state['values']['submitted']['nickname'] . '<br>'
    . $form_state['values']['submitted']['email'] . '<br>'
  ));  
}

/*-----------------------------------------------------------------------*/


function my_forms_callback() {
  $items = array();
  $items = drupal_get_form('my_forms_form');
  return $items;
}


function my_forms_form($form, &$form_state) {

  $form['firstname'] = array(
    '#type'      => 'textfield',
    '#title'     => t('your firstname'),
    '#size'      => 60,
    '#maxlength' => 60,
    '#required'  => false,  
  );
  $form['secondname'] = array(
    '#type'      => 'textfield',
    '#title'     => t('your secondname'),
    '#size'      => 60,
    '#maxlength' => 60,
    '#required'  => false, 
  );
  $form['nickname'] = array(
    '#type'      => 'textfield',
    '#title'     => t('your nickname'),
    '#size'      => 20,
    '#maxlength' => 20,
    '#required'  => TRUE, 
  );
  $form['email'] = array(
    '#type'      => 'textfield',
    '#title'     => 'e-mail',
    '#size'      => 60,
    '#maxlength' => 60,
    '#required'  => TRUE, 
  );
  $form['phone_number'] = array(
    '#type'        => 'textfield', 
    '#title'       => t('your phone number'),
    '#size'        => 12,
    '#maxlength'   => 12,
    '#description' => t('(ex: 380684445566)'),
    '#required'    => false,
  );
  $form['sex'] = array(
    '#type'    => 'radios',
    '#title'   => t('sex'),
    '#options' => array(
            1 => t('male'),
            2 => t('female')
    ),
    //'#options' => drupal_map_assoc(array(t('UK'), t('Other'))),
  );
  $form['country_select'] = array(
    '#type'    => 'select',
    '#title'   => t('country'),
    '#options' => array(
            0 => t('select country'),
            1 => t('Ukraine'),
            2 => t('Russia'),
            3 => t('USA'),
    ),
  );
  $form['message'] = array(
    '#type'     => 'textarea', 
    '#title'    => t('Message'),
    '#rows'     => 7,
    '#required' => false,
    '#cols'     => 40,
  );
  $form['agree_checkbox'] = array(
    '#type'     => 'checkbox',
    '#title'    => t('you agree to our Terms and that you have read our Privacy Policy'),
    '#required' => TRUE,
  );
  $form['submit_button'] = array(
    '#type'  => 'submit',
    '#value' => t('Click Here!'),
  );
  $form['some_fieldset'] = array(
    '#type'        => 'fieldset', 
    '#title'       => t('Privacy Policy'), 
    '#weight'      => 5, 
    '#collapsible' => TRUE, 
    '#collapsed'   => TRUE,
    '#value'       => t('This policy takes effect on Jan 1, 2016. The current policy can be found <a href="https://www.reddit.com/help/privacypolicy?v=33a67dd2-e2c6-11e4-807a-22000b248ffc">here</a>.'),
  );  
  return $form;
}


function my_forms_form_validate($form, &$form_state) {

  $mail = $form_state['values']['email'];
  if (!valid_email_address($mail)) {
    form_set_error('email', t('Please Enter a valid email address.'));
  }

  $phone_number = $form_state['values']['phone_number'];
  if (!($phone_number > 0) || strlen((string) $phone_number) < 12) {
    if (!empty($form_state['values']['phone_number'])) {
      form_set_error('phone_number', t('check your phone number'));
    }   
  }
}



function get_options_value($i, $form, $form_state) {
  $value = $form[$i]['#options'][$form_state['values'][$i]];
  if (empty($form_state['values'][$i])) {
    $value = '';
  }
  return $value;
}

function my_forms_form_submit($form, &$form_state) {
  //dsm($form_state['values']);
  drupal_set_message(t('The form has been submitted.<br>'
    . $form_state['values']['firstname'] . '<br>'
    . $form_state['values']['secondname'] . '<br>'
    . $form_state['values']['nickname'] . '<br>'
    . $form_state['values']['email'] . '<br>'
    . $form_state['values']['phone_number'] . '<br>'
    . get_options_value('country_select', $form, $form_state) . '<br>'
    . get_options_value('sex', $form, $form_state) . '<br>'
    . $form_state['values']['message'] . '<br>'
  ));
}
